apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: timescaledb:5432
    user: erebor
    jsonData:
      database: erebor
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: ${TIMESCALEDB_PASSWORD}
    editable: false
